### ISSUE TITLE
[captcha] Support multple domains

### ISSUE THREAD

**Issue by LaurenceJJones** [LaurenceJJones/crowdsec-spoa#1]
As from user issue in [reddit](https://www.reddit.com/r/CrowdSec/comments/1c4519j/crowdsec_and_captcha_on_haproxy_which_has/) has outlined a limitation in the current lua implementation. My thoughts so far is we could expose a configuration which looks like:

```yaml
captcha:
   - host: my.domain.net
     site_key: xyz
     site_secret: secret
     provider: recaptcha
   - host: my.domain.com
     site_key: xyz
     site_secret: secret
     provider: recaptcha
  - host: *.service.host
     site_key: xyz
     site_secret: secret
     provider: turnstile
```

The host is the host header that matches on either a string or a globbing pattern and then is served a template from this. However, each site will most likely want to grant a grace period per domain.
